l_spanish:
at_artifact_price_qwa_desc: "Calidad y Riqueza"
at_artifact_price_durability_desc: "Durabilidad"
at_artifact_price_destroy_desc: "No Menos que el Precio de Destrucción"
at_artifact_price_unique_desc: "Único"
at_artifact_price_tribal_desc: "Gobierno Tribal"
at_artifact_ask_price_player_desc: "Margen de Beneficio"
at_artifact_ask_price_ai_greed_desc: "Codicia del Vendedor"
at_artifact_bid_price_ai_greed_desc: "Codicia del Comprador"
at_artifact_bid_price_multiplier_desc: "Resultado del Regateo"
